# Generated by Django 4.2.5 on 2023-09-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('O', 'Орёл'), ('R', 'Решка')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
