# Generated by Django 4.2.5 on 2023-10-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_author_birthday"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "статью", "verbose_name_plural": "статьи"},
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "автора", "verbose_name_plural": "авторы"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "комментарий",
                "verbose_name_plural": "комментарии",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blog.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(max_length=100, verbose_name="Категория"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Текст статьи"),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название статьи"),
        ),
        migrations.AlterField(
            model_name="article",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
