# Generated by Django 4.2.5 on 2023-10-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_remove_order_good_order_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="good",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
