# Generated by Django 4.2.5 on 2023-09-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="good",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods",
                to="shop.good",
            ),
        ),
    ]
