# Generated by Django 4.2.5 on 2023-09-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_order_good"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="good",
        ),
        migrations.AddField(
            model_name="order",
            name="goods",
            field=models.ManyToManyField(related_name="goods", to="shop.good"),
        ),
    ]
