# Generated by Django 4.2.5 on 2023-10-05 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_good_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "клиента", "verbose_name_plural": "клиенты"},
        ),
        migrations.AlterModelOptions(
            name="good",
            options={"verbose_name": "товара", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "заказа", "verbose_name_plural": "заказы"},
        ),
    ]
